version: "3.2"
services:

 db_conversor:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaBanco
    ports:
     - "3306:3306"

 conversor:
    build: ./apl-api-genus-moedas
    ports:
     - "5001:5000"
